remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have on


title: Lau Johansson
description: Lau Johansson's Data Science & Deep Learning Projects
#show_downloads: true
#google_analytics:
#theme: jekyll-theme-cayman